#pragma kernel Main

RWTexture2D<float> ColliderResult;
RWStructuredBuffer<float3> MeshVertices;

int _TextureSize;
float _TerrainHeight;

/**
 * Saves the RT values into the MeshVertices array.
 * Be careful, this only works right if the RT has the same size like the mash plane!
 */
[numthreads(32, 32, 1)]
void Main (uint3 id : SV_DispatchThreadID)
{
	uint flatIndex = _TextureSize * id.y + id.x;
	MeshVertices[flatIndex].z = -ColliderResult[id.xy].r * _TerrainHeight;
}
